# Fundamental concepts of tensors using tensorflow

* Introducing Tesnors
* Getting infos from Tesnors
* Manipulating Tesnors
* Tensors and numpy
* Using @tf.function (a way to speed up regular python functions)
* Using GPUs with Tensorflow (or TPUs)
* Excercises

## Introduction to Tensors

In [1]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimension of the vector
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix 
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
#Let's create a tensor
tensor = tf.constant([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]], [[9., 10.], [11., 12.]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)>

In [11]:
tensor.ndim

3

* A scalar is a single number
* A vector is a umber with direction (e.g windspeed with direction)
* A matrix is a 2-dimensional array of numbers
* A tensor is an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, etc)

### Creating tensors with `tf.varaiable`

In [12]:
# Another way to create tensor 
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Changing elements in the changeable tensor
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# Changing elements in the unchangeable tensor
unchangeable_tensor[0].assign(7)

### Create random tensors

Random tensors are tensors of some arbitrary size which contain random numbers

In [14]:
# create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))

# are they equal? They are because we set the seed
random_1, random_2, random_2==random_1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [15]:
# Shuffle a tensor (Valuable when we want to shuffle a data, better for learning by the ML)
not_shuffled = tf.constant([[10, 7], [3, 4], [8, 11]])

#shuffle the non-shuffled tensor
tf.random.shuffle(not_shuffled) # shuffle aound the first dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 8, 11]], dtype=int32)>

In [16]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 8, 11]], dtype=int32)>

In [17]:
# setting the seed
tf.random.set_seed(42) #global level seed
tf.random.shuffle(not_shuffled, seed=42) #operational level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 8, 11]], dtype=int32)>

**Exercise:** Read the doc of tensorflow random seed generation.

### Other ways to make tensors

In [18]:
# CREATE TENSOR OF ALL ONES
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [19]:
# CREATE TENSORS OF ALL ZEROS
tf.zeros([4,3])

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The main difference between Numpy arrays and Tensorflow tensors is that tensors can be run faster on a GPU for numerical computing

In [20]:
# Change numpy arrays to tensors 
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [21]:
A = tf.constant(numpy_A, shape=(4, 2, 3))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]],
 
        [[19, 20, 21],
         [22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [22]:
A.ndim

3

### Getting information from tensors

* Shape 
* Rank
* Axis or dimensions
* Size

In [23]:
# Create a rank 4 tensor

rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank_4_tensor.ndim

4

In [25]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [26]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [27]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [28]:
2*3*4*5

120

In [29]:
# Get various attributes of tensors

print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor)) 
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): tf.Tensor(120, shape=(), dtype=int32)
Total number of elements (2*3*4*5): 120


### Indexing Tesnors

Tenors can be indexed just like python lists.

In [30]:
# Get the first two elements of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [31]:
# Get the first element from each dimension from each index, except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7], [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [33]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [34]:
#Get the last item of each row of the rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [35]:
# Add an extra dimension to the rank 2 tensor, i.e turn it to rank 3 without chainging the contents
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # the 3 dots means for every previous axes before the last axis
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [36]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) #-1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [37]:
#Expand the zero axis
tf.expand_dims(rank_2_tensor, axis=0) #expands the zero axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic operations**



In [38]:
# add a value to a tensor
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10 # original tensor remains unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [39]:
# multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [40]:
# subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [41]:
#using built in tensor function to multiply
tf.multiply(tensor, 10) # original tensor remains unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

In ML, matrix multiplication is one of the most common operations.

In [42]:
#matrix mult in tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [43]:
#matrix multiplication with python operator '@
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [44]:
tensor * tensor #Element wise multiplication. Just like matrix squared

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [45]:
# create a (3, 2) tensor
X = tf.constant([[1, 2], [3, 4], [5, 6]])
Y = tf.constant([[7, 8], [9, 10], [11, 12]])
X, Y
#Inner dimensions do not match

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [46]:
#transpose Y to ensure the inner dimensions match X=(3,2) and Y - (2, 3)
Y = tf.transpose(Y)
Y


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [47]:
tf.matmul(X, Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

**The Dot Product**

Matrix Multiplication is also refered to as dot product. Thus multiplying two matrices can be done by
* `tf.matmul()`
* `tf.tensordot()`

### Change the datatype of a tensor

In [48]:
#create a new tensor with default datatyope (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [49]:
#create a new tensor with default datatyope (int32)
C = tf.constant([1, 7])
C.dtype

tf.int32

In [50]:
#reduce precision to 16. 16 bits will run faster than 32 bits when we have lots of data
# Mixed precision of 16 and 32 will make model run faster during training
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [51]:
#change from int32 to float 32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

### Aggregating Tensors

* Aggregating means condensing tensors from multiple values down to a smaller amount of values

In [52]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [53]:
tf.abs(D) # absolute values of D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following form of aggregation

* Get minimum, maximum, mean and sum of a tensor

In [54]:
# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([49,  3, 29, 99, 37, 29,  6, 12, 72, 27, 72, 92, 81, 88, 43, 23, 95,
       60, 21, 88, 34, 54, 57, 92, 38, 11, 96, 23, 39, 95, 14, 21,  7, 68,
        4, 71, 30, 81, 47, 24, 21, 33, 76, 38,  4, 58, 43,  0, 27, 85])>

In [55]:

# Find the minimum
tf.reduce_min(E).numpy()

0

In [56]:

# Find the maximum
tf.reduce_max(E).numpy()

99

In [57]:

# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [58]:

# Find the sum
tf.reduce_sum(E).numpy()

2317

In [59]:
# FIND THE VARAINCE
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=906>

In [60]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=906.2644>

In [61]:
 # FIND THE STD
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.104225>

**Find the positional maximum and minimum of a tensor**

In [62]:
#create a new tensor to find positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50], seed=42)
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.4163028 , 0.26858163, 0.47968316, 0.36457133, 0.95471144,
       0.9418646 , 0.61483395, 0.35842144, 0.5936024 , 0.21551096,
       0.07745171, 0.57921314, 0.29180396, 0.26718032, 0.37012458,
       0.7161033 , 0.45877767, 0.11764562, 0.21073711, 0.5441973 ,
       0.9898069 , 0.38395858, 0.04683566, 0.8718462 , 0.25881708,
       0.873135  , 0.64698434, 0.41981232, 0.24148273, 0.09550059,
       0.9820819 , 0.1570208 , 0.2997682 , 0.36795306, 0.9453716 ,
       0.11056781, 0.52287626, 0.8305441 , 0.0020721 , 0.9594034 ,
       0.85630023, 0.3944497 , 0.22028875, 0.67066073, 0.01875746,
       0.48057055, 0.5953454 , 0.6847329 , 0.18988943, 0.12489867],
      dtype=float32)>

In [63]:
#Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=20>

In [64]:
#index the largest value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9898069>

In [65]:
#check equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [66]:
#Find the positional min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=38>

### Squeezing a tensor (removing all single dimensions)

In [68]:
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [69]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [70]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding tensors

In [71]:
# create a list of indicees
some_list = [0, 1, 2, 3] #could be red, green, blue , and purple

#one hot encode our list of indices
tf.one_hot(some_list, 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [74]:
# specify custom values for onehot encoding
tf.one_hot(some_list, depth=4, on_value = 'Y', off_value = 'N')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Y', b'N', b'N', b'N'],
       [b'N', b'Y', b'N', b'N'],
       [b'N', b'N', b'Y', b'N'],
       [b'N', b'N', b'N', b'Y']], dtype=object)>

### squaring, log, square root

In [75]:
# create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [76]:
# square the tensor
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [78]:
#find square root(method requires non int type)
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [81]:
#find the log (method requires non int type)
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

* Tensorflow interract beautifully with numpy arrays

In [82]:
#create a tesnor dirrectly from a Numpy array
J = tf.constant(np.array([2., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 2.,  7., 10.])>

In [83]:
# convert tensor to np array
np.array(J), type(np.array(J))

(array([ 2.,  7., 10.]), numpy.ndarray)

In [84]:
# convert tensor J to a Numpy array (another way)
J.numpy(), type(J.numpy())

(array([ 2.,  7., 10.]), numpy.ndarray)

In [85]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([2., 7., 10.])) #flaot64
tensor_J = tf.constant([2., 7., 10.]) #float32
numpy_J, tensor_J

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 2.,  7., 10.])>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2.,  7., 10.], dtype=float32)>)

###  Using @tf.function

This is an example of a decorator function. In the @tf.function decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with @tf.function, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).


In [86]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [87]:

# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [89]:
#checking access to GPU. 
#If the below outputs an empty array (or nothing), it means you don't have access to a GPU (or at least TensorFlow can't find it).
print(tf.config.list_physical_devices('GPU'))

[]
